### PR TITLE
Make no_std compatible

### PR DESCRIPTION
**Pull request by simpsoneric**
This PR is a WIP for making the crate `no_std` compatible.

I would like to use nom-derive in a no_std context, and have the following attempt below.  

- It compiles and builds for my embedded target.
- It passes the same `cargo test` results as the current master

I'm not sure of the larger context for how you'd like the crate to operate.  Thought I'd pass along the "request for feature".

### CODE REVIEW

**Comment by simpsoneric** [comment]
@chifflier, would you like me to keep this PR up to date by rebasing or merging?

**Comment by chifflier** [comment]
Hi,
Sorry I somehow missed this and broke this PR in the recent commits.
I am interested in adding support for `no_std`. Can you rebase and re-send? Thanks!

**Comment by dne** [comment]
I'm not @simpsoneric, but I managed to rebase this PR to make v0.10.0 build for `no_std`. I also added dne/nom-derive@1331a4e6e26f060ae3ea70ef003f94082beb721d.

Unfortunately, nom 7 broke `no_std` support but there's trivial fix, Geal/nom@615e6a441e4644377f1567d2ed789118ef07473f, that's not in a release yet. The current nom master branch works though.

**Comment by simpsoneric** [comment]
@dne, thanks for taking the time to update this.  Last week I started the update, but also ran into the nom7 `no_std` issue, thanks for moving it forward.

Does it make more sense to let the changes to https://github.com/dne/nom/commits/7.0-no_std get merged to upstream nom before rebasing this?  (Or just create a new PR based on your branch, no preferences here).

**Comment by dne** [comment]
Well, the necessary changes are already in nom's master branch; it's only a release that's missing. I posted a comment in Geal/nom#1371 asking about that.

**Comment by ball-hayden** [comment]
Sorry! I thought I'd have a look to see how hard it would be and got carried away 😆

**Pull request closed without merging**
