### PR TITLE
import Span from proc_macro2 instead of syn

### PR DESCRIPTION
**Pull request by kcking**
appears to fix https://github.com/rust-bakery/nom-derive/issues/11

### CODE REVIEW

**Comment by chifflier** [comment]
Merged, thanks!

**Comment by FreeMasen** [comment]
I am wondering if this could also be backported into version 0.6? I have setup a fork/branch with the changes but would need a branch to merge it into.

https://github.com/FreeMasen/nom-derive/tree/backport-syn-fix

**Comment by chifflier** [comment]
> I am wondering if this could also be backported into version 0.6? I have setup a fork/branch with the changes but would need a branch to merge it into.

Sure, backported in 970488917a09d320e5a0f36b27ebc29ba72ce0a0
I'll upload a release to crates.io

**Comment by FreeMasen** [comment]
Thanks!

**Pull request merged**
